### ISSUE TITLE
Fat-Free Fox do not change settings automatically

### ISSUE THREAD

**Issue by davidhedlund** [oyenamit/fat-free-firefox#1]
To quote the Fat-Free Fox documentation about WebRTC: "WebRTC Private IP Address Leak: Note that enabling this option will only block private IP address leak due to WebRTC. It will not disable WebRTC completely. Firefox Hello would still be usable as before."

Why is this feature not enabled by default?

**Comment by oyenamit** [comment]
Fat-Free Fox will never enable a feature by default. It will inform and educate the users and then let them make a choice. That is the core philosophy of this add-on. Also, I would like to avoid a situation where a feature is enabled by default but it causes incompatibility/inconvenience to the user and then the user discovers that Fat-Free Fox is the culprit because it has secretly changed some setting.

**Comment by davidhedlund** [comment]
@oyenamit Can you please state something like "Fat-Free Fox do not change any setting but give users a choice to do so by them selves." in the AMO description?

**Comment by oyenamit** [comment]
Sure, I have added a note to the AMO description.

**Comment by davidhedlund** [comment]
@oyenamit Thank you.
