### ISSUE TITLE
Block Push notifications: broken?

### ISSUE THREAD

**Issue by woctezuma** [oyenamit/fat-free-firefox#4]
Whichever setting is chosen for the push notifications in Fat Free Fox, I notice the popup regarding push notifications in the top left corner of the screen when I go to this website: https://steamdb.info/sales/

I am using Firefox 50.0b10 (Beta), Fat Free Fox 2.3 and various other addons.

**Comment by oyenamit** [comment]
Thank you for your feedback.

What you are seeing are [Web Notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API). Fat-Free Fox blocks only [Push Notifications](https://developer.mozilla.org/en/docs/Web/API/Push_API).
The difference is that Web Notifications are just a way for a website to display a message to the user only while the site is open. However, Push Notifications can be shown even if you close that site.
For example, [goroost](https://goroost.com/try-web-push) uses Push notifications and they will not be shown if you disable notifications in Fat-Free Fox.

I understand that this is confusing for the end user because the Firefox UI for these notifications is the same.

**Comment by woctezuma** [comment]
Thank you for the clarification.
